CXX = g++

SRC = generator.cpp ../../evaluate/timespecOperators.cpp

IFLAGS = 

STATICLIBS =

DSTNAME = generator

all:
	$(CXX) -Wall -g $(SRC) $(IFLAGS) $(STATICLIBS) -o $(DSTNAME)

clean:
	rm -f *.dat $(DSTNAME)

